### ISSUE TITLE
bitmap/bitmap.go

### ISSUE THREAD

**Issue by axet** [anacrolix/missinggo#10]
Hello!

bitmap missing serialization mecanics. Original rb has WriteTo/ReadFrom method.

https://github.com/RoaringBitmap/roaring

**Comment by anacrolix** [comment]
This is really just a wrapper with what I use, so I can swap it out. I'm not sure I want serialization of bitmaps to be exposed on the type. What use case do you have?

**Comment by axet** [comment]
I solved it using torrent calls. Just mised some flexibility. Not important anymore
