### ISSUE TITLE
missinggo/httptoo broken

### ISSUE THREAD

**Issue by ewhal** [anacrolix/missinggo#11]
# github.com/anacrolix/missinggo/httptoo
../../anacrolix/missinggo/httptoo/inproc_roundtrip.go:23: cannot use responseWriter literal (type *responseWriter) as type interface { CloseNotify() <-chan bool; Header() http.Header; Write([]byte) (int, error); WriteHeader(int) } in assignment:
	*responseWriter does not implement interface { CloseNotify() <-chan bool; Header() http.Header; Write([]byte) (int, error); WriteHeader(int) } (missing CloseNotify method)

**Comment by anacrolix** [comment]
Thanks. I was too hasty with this commit.
