### ISSUE TITLE
Rename goleaktest.go to goleak_test.go

### ISSUE THREAD

**Issue by sudarshan-reddy** [anacrolix/missinggo#12]
Using this package during a `flag.parse()` would result in testing values being listed as well when --help is run. 

Env:
Go 1.8.3

OS: 
Sierra (Darwin Kernel Version 16.4.0)

```
-test.bench regexp
        run only benchmarks matching regexp
  -test.benchmem
        print memory allocations for benchmarks
  -test.benchtime d
        run each benchmark for duration d (default 1s)
  -test.blockprofile file
        write a goroutine blocking profile to file
  -test.blockprofilerate rate
        set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
  -test.count n
        run tests and benchmarks n times (default 1)
  -test.coverprofile file
        write a coverage profile to file
  -test.cpu list
        comma-separated list of cpu counts to run each test with
  -test.cpuprofile file
        write a cpu profile to file
  -test.memprofile file
        write a memory profile to file
  -test.memprofilerate rate
        set memory profiling rate (see runtime.MemProfileRate)
  -test.mutexprofile string
        write a mutex contention profile to the named file after execution
  -test.mutexprofilefraction int
        if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
  -test.outputdir dir
        write profiles to dir
  -test.parallel n
        run at most n tests in parallel (default 8)
  -test.run regexp
        run only tests and examples matching regexp
  -test.short
        run smaller test suite to save time
  -test.timeout d
        fail test binary execution after duration d (0 means unlimited)
  -test.trace file
        write an execution trace to file
  -test.v
        verbose: print additional output
```

**Comment by anacrolix** [comment]
Thanks for catching this

**Comment by anacrolix** [comment]
This seems non-trivial. When packages are compiled for testing, that doesn't automatically trigger _test.go files to be compiled for dependent packages too. So if GoroutineLeakCheck is in a _test.go file, it is never available to other packages.

**Comment by sudarshan-reddy** [comment]
@anacrolix I noticed you only use `t.Logf`. Does it make sense to have this file not use `testing` and pass the logs upstream via a channel or the like? If you think that's a something viable, I could make the change on a fork perhaps. 

It would however render torrent/vendor/github.com/anacrolix/utp/utp_test.go backwards incompatible with an update.

**Comment by anacrolix** [comment]
I realised I can just move the function into a package used only by other testing code, thereby removing the testing import that causes these extra flags in regular code.
