### ISSUE TITLE
conntrack: double lock on EntryHandle

### ISSUE THREAD

**Issue by etix** [anacrolix/missinggo#14]
After investigating an issue with an always increasing number of goroutines locked in the same `Wait()` function I ended up on the following double-lock on `eh.added`:
https://github.com/anacrolix/missinggo/blob/118c32fc17c87eaf763550916763c4ca37249ac6/conntrack/instance.go#L174-L178

I don't know if this is expected but I find it quite dubious.

**Comment by anacrolix** [comment]
The mutex is locked to make a subsequent Lock block until the lock is Unlocked [here](https://github.com/anacrolix/missinggo/blob/cb6c13c0090099c4d350be2679d11c190c6f10a1/conntrack/instance.go#L146). Did you find any bugs related to the conntrack package, or just a very high number of waiting goroutines?

**Comment by etix** [comment]
I see. I suggest you add a comment around here to clarify the behavior.

I'm not yet sure there is a bug, but I see an ever increasing number of goroutines until the OOM kicks. The more torrents are downloaded in parallel the faster the issue arise.

Thanks for the clarification though!

**Comment by anacrolix** [comment]
> I suggest you add a comment around here to clarify the behavior.

Good idea, thanks.

The number of goroutines does typically grow to the order of several tens of thousands. Without the race detector enabled, the memory use shouldn't be too significant. Please provide some metrics if you have any.
