### ISSUE TITLE
remove bradfitz.iter.N from iter.n

### ISSUE THREAD

**Issue by RizzerOnGitHub** [anacrolix/missinggo#15]
github.com/bradfitz/iter is a one line piece of code created for education and not intended for use as a package by real code. Treating it as a real package puts unnecessary strain on packaging infrastructure.

Please replace the reference to iter.N in missinggo/iter/n.go to provide the actual slice that is needed:

    package iter
    
    func N(n int) []struct{} {
            return make([]struct{}, n)
    }

**Comment by anacrolix** [comment]
That's true, but there's a lot of other places in `missinggo` that depend on it. And `bradfitz/iter` actually contains a test that ensures there's no corresponding allocation, so it's not entirely without value.

**Comment by anacrolix** [comment]
See also https://github.com/bradfitz/iter/issues/7.

**Comment by anacrolix** [comment]
Let me know if you have further insight.

**Comment by RizzerOnGitHub** [comment]
Thanks Matt, for following it up.
