### ISSUE TITLE
undefined reflect.StructOf

### ISSUE THREAD

**Issue by liangmingyuanneo** [anacrolix/missinggo#9]
This project has used reflect.StructOf. But when I compiler the project, it prints that reflect.StructOf is not defined. I have searched the Internet and find there is no this struct. Do you meet this problem?

**Comment by anacrolix** [comment]
http://tip.golang.org/pkg/reflect/#StructOf was only added to golang/go master 2 weeks ago. I've fallen back to more generic behaviour that should work for any Go version in the meanwhile. https://github.com/anacrolix/missinggo/commit/2a6ebc308589efb4482485ad396a9fd1f0f658d2
